## Cassandra Operator Image
##
image:
  repository: orangeopensource/cassandra-k8s-operator
  tag: 0.3.1-master
  pullPolicy: Always
  imagePullSecrets:
    enabled: true
    name: advisedev

## Team
##
team: devops

## Prometheus-operator resource limits & requests
## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 1
    memory: 512Mi


## If true, create & use RBAC resources
##
rbacEnable: true

## if true deploy service for metrics access
metricService: false

debug:
  enabled: false
