apiVersion: v1
description: A Helm chart for MultiCassKop - the Orange Multiple Cassandra Kubernetes operator
name: multi-casskop
home: https://github.com/Orange-OpenSource/casskop/multi-casskop
sources:
  - https://github.com/Orange-OpenSource/casskop/multi-casskop
version: 0.5.6
appVersion: 0.5.6-release
maintainers:
  - name: allamand
    email: sebastien.allamand@orange.com
  - name: cscetbon
    email: cscetbon.ext@orange.com
  - name: jal06
    email: jeanarmel.luce@orange.com
  - name: erdrix
    email: aguitton.ext@orange.com
  - name: fdehay
    email: franck.dehay@orange.com
keywords:
- operator
- cassandra
- casskop
- multi-casskop
- multi-clusters
