apiVersion: v1
description: A Helm chart for MultiCassKop - the Orange Multiple Cassandra Kubernetes operator
name: multi-casskop
home: https://github.com/Orange-OpenSource/casskop/multi-casskop
sources:
  - https://github.com/Orange-OpenSource/casskop/multi-casskop
version: 1.1.3
appVersion: 1.1.3-release
maintainers:
  - name: allamand
    email: sebastien.allamand@orange.com
  - name: cscetbon
    email: cscetbon@gmail.com
  - name: jal06
    email: jeanarmel.luce@orange.com
  - name: erdrix
    email: aguitton.ext@orange.com
  - name: fdehay
    email: franck.dehay@orange.com
  - name: PERES-Richard
    email: richardperes.info@gmail.com
keywords:
- operator
- cassandra
- casskop
- multi-casskop
- multi-clusters
